service: database-sync

custom:
  pythonRequirements:
    dockerizePip: false


package:
  exclude:
    - venv/**
    - node_modules/**

provider:
  name: aws
  vpc:
    securityGroupIds:
      - ${file(env/config.yml).SECURITY_GROUP}
    subnetIds:
      - ${file(env/config.yml).SUBNET_1}
      - ${file(env/config.yml).SUBNET_2}
      - ${file(env/config.yml).SUBNET_3}
  timeout: 900
  runtime: python3.6
  region: eu-west-1

  environment: ${file(env/config.yml)}


functions:
  syncHourly:
    handler: db_sync_handler.sync_hourly
    events:
      - schedule:
          rate: cron(0 0 * ? * *)
  syncDaily:
    handler: db_sync_handler.sync_daily
    events:
      - schedule:
          rate: cron(0 0 0 * * ?)
          
          
#   execSqlExecuter:
#     handler: file_sync_handler.script_to_be_executed
#     events:
#       - schedule:
#           rate: cron(54 2 * * ? *)

iamRoleStatements:
  - Effect: Allow
    Action:
    - rds:*
    Resource: "*"

plugins:
  - serverless-python-requirements
