SECURITY_GROUP: ${SECURITY_GROUP}
SUBNET_1: ${SUBNET_1}
SUBNET_2: ${SUBNET_2}
SUBNET_3: ${SUBNET_3}

LAMBDA_TASK_ROOT: ${LAMBDA_TASK_ROOT}
SOURCE_HOST: ${SOURCE_HOST}
SOURCE_USER: ${SOURCE_USER}
SOURCE_PASS: ${SOURCE_PASS}
SOURCE_DB: ${SOURCE_DB}
TARGET_HOST: ${TARGET_HOST}
TARGET_USER: ${TARGET_USER}
TARGET_PASS: ${TARGET_PASS}
TARGET_DB: ${TARGET_DB}

TABLE_LIST_DAILY: ${TABLE_LIST_DAILY}
TABLE_LIST_HOURLY: ${TABLE_LIST_HOURLY}